name: Build and Deploy ASP.NET Core to FTP

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # adjust to your version

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 190.92.174.109
        username: satyam
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish
        server-dir: /rbill.adlsoftcodes.com/

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Deployment Success:AdlSoftCodes
        to: satyam0297@gmail.com
        from: AdlSoftCodes <${{ secrets.EMAIL_USERNAME }}>
        body: |
          ✅ Your site (rbill.adlsoftcodes.com) was successfully deployed.
          - Date: ${{ steps.date.outputs.date }}
          - Repo: ${{ github.repository }}
          - Commit: ${{ github.sha }}

